# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biblioteca.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.F_superior = QtWidgets.QFrame(self.widget_3)
        self.F_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.F_superior.setStyleSheet("QFrame{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"QPushButton{\n"
"background-color: #000000ff ;\n"
"border-radius:20px;\n"
"font: 60 7pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(61,61,61);\n"
"border-radius:20px;\n"
"font: 60 7pt \"Arial Black\";\n"
"}")
        self.F_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_superior.setObjectName("F_superior")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.F_superior)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.F_superior)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/menu (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.F_superior)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/notificacion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_17.addWidget(self.F_superior)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("\n"
"QWidget {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 80 12pt \"Arial Black\";\n"
"    color: rgb(50, 50, 50); /* Texto en gris oscuro */\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); /* Borde negro */\n"
"    background-color: rgb(245, 245, 245); /* Fondo ligeramente gris */\n"
"    color: rgb(50, 50, 50); /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    padding: 5px; /* Espaciado interno */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 0, 0); /* Borde negro más grueso al enfocar */\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco al enfocar */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent; /* Sin fondo */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    color: rgb(0, 0, 0); /* Texto negro */\n"
"    font: 60 9pt \"Arial Black\"; /* Fuente en negrita */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: transparent; /* Sin fondo al pasar el cursor */\n"
"    color: rgb(0, 0, 0); /* Texto negro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: transparent; /* Sin fondo al presionar */\n"
"    color: rgb(0, 0, 0); /* Texto negro */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: transparent; /* Sin fondo */\n"
"    color: rgb(150, 150, 150); /* Texto gris claro */\n"
"}\n"
"/* spinxbox*/\n"
"QSpinBox {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"    border: 1px solid rgb(200, 200, 200); /* Borde gris claro */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: rgb(50, 50, 50); /* Texto gris oscuro */\n"
"    font: 75 12pt \"Arial\"; /* Fuente simple */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgb(0, 123, 255); /* Borde azul al enfocar */\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    color: rgb(0, 92, 204); /* Azul oscuro al pasar el cursor */\n"
"}\n"
"/*DateEdit*/\n"
"QDateEdit {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"    border: 1px solid rgb(200, 200, 200); /* Borde gris claro */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: rgb(50, 50, 50); /* Texto gris oscuro */\n"
"    font: 75 12pt \"Arial\"; /* Fuente simple */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    width: 150px; /* Ancho fijo */\n"
"}\n"
"QDateEdit:focus {\n"
"    border: 1px solid rgb(0, 123, 255); /* Borde azul al enfocar */\n"
"    background-color: rgb(240, 240, 240); /* Fondo ligeramente gris al enfocar */\n"
"}\n"
"QDateEdit::down-arrow:hover {\n"
"    background-color: rgb(240, 240, 240); /* Fondo al pasar el cursor */\n"
"}\n"
"\n"
"\n"
"/* Combobox*/\n"
"QComboBox {\n"
"    \n"
"    border: 1px solid rgb(200, 200, 200); /* Borde gris claro */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: rgb(50, 50, 50); /* Texto gris oscuro */\n"
"    font: 75 12pt \"Arial\"; /* Fuente simple */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo */\n"
"    selection-background-color: rgb(0, 123, 255); /* Color de fondo de la selección */\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid rgb(0, 123, 255); /* Borde azul al enfocar */\n"
"    background-color: rgb(240, 240, 240); /* Fondo ligeramente gris al enfocar */\n"
"}\n"
"QComboBox::down-arrow:hover {\n"
"    background-color: rgb(0, 123, 255); /* Fondo azul al pasar el cursor */\n"
"    border-left: 4px solid rgb(255, 255, 255); /* Flecha blanca cuando el cursor pasa sobre ella */\n"
"}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Dashborar = QtWidgets.QWidget()
        self.Dashborar.setObjectName("Dashborar")
        self.label_4 = QtWidgets.QLabel(self.Dashborar)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.Dashborar)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 801, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setStyleSheet("background-color: rgb(255, 70, 53);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 101, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setMinimumSize(QtCore.QSize(10, 10))
        self.label_39.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_39.setFont(font)
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap(":/newPrefix/pila-de-libros.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_35.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_38.setMinimumSize(QtCore.QSize(0, 0))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_35.addWidget(self.label_38)
        self.verticalLayout_9.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_39.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_5.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 10, 101, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_10.addWidget(self.label_58)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_60.setMinimumSize(QtCore.QSize(10, 10))
        self.label_60.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_60.setFont(font)
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap(":/newPrefix/seguidores.png"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_36.addWidget(self.label_60)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_59.setMinimumSize(QtCore.QSize(0, 0))
        self.label_59.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_36.addWidget(self.label_59)
        self.verticalLayout_10.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_39.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 10, 121, 91))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_11.addWidget(self.label_40)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_42.setMinimumSize(QtCore.QSize(10, 10))
        self.label_42.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_42.setFont(font)
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap(":/newPrefix/bookcrossing_10292218.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_37.addWidget(self.label_42)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_41.setMinimumSize(QtCore.QSize(0, 0))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_37.addWidget(self.label_41)
        self.verticalLayout_11.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_39.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 10, 121, 91))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_12.addWidget(self.label_27)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_30.setMinimumSize(QtCore.QSize(10, 10))
        self.label_30.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/newPrefix/libroggg.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_38.addWidget(self.label_30)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_29.setMinimumSize(QtCore.QSize(0, 0))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_38.addWidget(self.label_29)
        self.verticalLayout_12.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.Dashborar)
        self.Reporte = QtWidgets.QWidget()
        self.Reporte.setObjectName("Reporte")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.Reporte)
        self.stackedWidget_2.setGeometry(QtCore.QRect(1, 38, 851, 481))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.ReporteGeneral = QtWidgets.QWidget()
        self.ReporteGeneral.setObjectName("ReporteGeneral")
        self.layoutWidget5 = QtWidgets.QWidget(self.ReporteGeneral)
        self.layoutWidget5.setGeometry(QtCore.QRect(50, 270, 761, 42))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_48.addWidget(self.pushButton_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem2)
        self.layoutWidget6 = QtWidgets.QWidget(self.ReporteGeneral)
        self.layoutWidget6.setGeometry(QtCore.QRect(50, 70, 761, 191))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_42.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_42.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_42.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_42.addWidget(self.checkBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_43.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_43.addWidget(self.checkBox_7)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_43.addWidget(self.checkBox_6)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_43.addWidget(self.checkBox_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_44.addWidget(self.checkBox_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_44)
        self.layoutWidget7 = QtWidgets.QWidget(self.ReporteGeneral)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 30, 712, 36))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel {\n"
"    font: 80 10pt \"Arial Black\";\n"
"    color: rgb(50, 50, 50); /* Texto en gris oscuro */\n"
"    border: 0px;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_45.addWidget(self.label_25)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.horizontalLayout_47.addLayout(self.horizontalLayout_46)
        self.stackedWidget_2.addWidget(self.ReporteGeneral)
        self.Reportelector = QtWidgets.QWidget()
        self.Reportelector.setObjectName("Reportelector")
        self.layoutWidget8 = QtWidgets.QWidget(self.Reportelector)
        self.layoutWidget8.setGeometry(QtCore.QRect(30, 50, 691, 151))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_51.addWidget(self.label_54)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_50.addWidget(self.lineEdit_33)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_21.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 123, 255); /* Azul */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(51, 153, 255); /* Azul más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_50.addWidget(self.pushButton_21)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_50)
        self.verticalLayout_4.addLayout(self.horizontalLayout_51)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(167771, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_4.addWidget(self.lineEdit_6)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem3)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_52.addWidget(self.pushButton_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_52)
        self.stackedWidget_2.addWidget(self.Reportelector)
        self.layoutWidget9 = QtWidgets.QWidget(self.Reporte)
        self.layoutWidget9.setGeometry(QtCore.QRect(1, 1, 801, 31))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_40.addWidget(self.pushButton_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget9)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_40.addWidget(self.pushButton_8)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_40)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.Reporte)
        self.Devoluciones = QtWidgets.QWidget()
        self.Devoluciones.setObjectName("Devoluciones")
        self.label_5 = QtWidgets.QLabel(self.Devoluciones)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 221, 31))
        self.label_5.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 80 12pt \"Arial Black\";\n"
"    color: rgb(50, 50, 50); /* Texto en gris oscuro */\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); /* Borde negro */\n"
"    background-color: rgb(245, 245, 245); /* Fondo ligeramente gris */\n"
"    color: rgb(50, 50, 50); /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    padding: 5px; /* Espaciado interno */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 0, 0); /* Borde negro más grueso al enfocar */\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco al enfocar */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(34, 139, 34); /* Verde por defecto */\n"
"    border: 1px solid rgb(28, 115, 28); /* Borde verde oscuro */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    color: rgb(255, 255, 255); /* Texto blanco */\n"
"    font: 60 9pt \"Arial Black\"; /* Fuente en negrita */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 205, 50); /* Verde más claro al pasar el cursor */\n"
"    border: 1px solid rgb(34, 139, 34); /* Borde verde por contraste */\n"
"    color: rgb(255, 255, 255); /* Texto blanco */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 100, 0); /* Verde más oscuro al presionar */\n"
"    border: 1px solid rgb(0, 80, 0); /* Borde más oscuro */\n"
"    color: rgb(255, 255, 255); /* Texto blanco */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(200, 200, 200); /* Fondo gris para desactivado */\n"
"    color: rgb(150, 150, 150); /* Texto gris claro */\n"
"    border: 1px solid rgb(200, 200, 200); /* Borde gris claro */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.layoutWidget10 = QtWidgets.QWidget(self.Devoluciones)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 40, 801, 461))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit.setMaximumSize(QtCore.QSize(167771, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget10)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 123, 255); /* Azul */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(51, 153, 255); /* Azul más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(167771, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_18.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(167771, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_18.addWidget(self.lineEdit_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.dateEdit_11 = QtWidgets.QDateEdit(self.layoutWidget10)
        self.dateEdit_11.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEdit_11.setStyleSheet("")
        self.dateEdit_11.setCalendarPopup(True)
        self.dateEdit_11.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_11.setObjectName("dateEdit_11")
        self.horizontalLayout_7.addWidget(self.dateEdit_11)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget10)
        self.comboBox.setMinimumSize(QtCore.QSize(172, 30))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_19.addWidget(self.comboBox)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget10)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        spacerItem7 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.Devoluciones)
        self.Prestamos = QtWidgets.QWidget()
        self.Prestamos.setObjectName("Prestamos")
        self.label_28 = QtWidgets.QLabel(self.Prestamos)
        self.label_28.setGeometry(QtCore.QRect(9, 9, 319, 23))
        self.label_28.setMaximumSize(QtCore.QSize(400, 30))
        self.label_28.setObjectName("label_28")
        self.layoutWidget11 = QtWidgets.QWidget(self.Prestamos)
        self.layoutWidget11.setGeometry(QtCore.QRect(11, 48, 821, 451))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_13.addWidget(self.label_48)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_12.addWidget(self.lineEdit_30)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget11)
        self.pushButton_19.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 123, 255); /* Azul */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(51, 153, 255); /* Azul más claro */\n"
"    color: white;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_12.addWidget(self.pushButton_19)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_49 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_14.addWidget(self.label_49)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_14.addWidget(self.lineEdit_31)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_50.setMaximumSize(QtCore.QSize(300, 50))
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_15.addWidget(self.label_50)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget11)
        self.comboBox_3.setMaximumSize(QtCore.QSize(600, 30))
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_15.addWidget(self.comboBox_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_16.addWidget(self.label_51)
        self.dateEdit_9 = QtWidgets.QDateEdit(self.layoutWidget11)
        self.dateEdit_9.setCalendarPopup(True)
        self.dateEdit_9.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_9.setObjectName("dateEdit_9")
        self.horizontalLayout_16.addWidget(self.dateEdit_9)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_17.addWidget(self.label_52)
        self.dateEdit_10 = QtWidgets.QDateEdit(self.layoutWidget11)
        self.dateEdit_10.setCalendarPopup(True)
        self.dateEdit_10.setObjectName("dateEdit_10")
        self.horizontalLayout_17.addWidget(self.dateEdit_10)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_17)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 0, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget11)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_5.addWidget(self.spinBox_5, 0, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem8 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.btn_reg_prestamos = QtWidgets.QPushButton(self.layoutWidget11)
        self.btn_reg_prestamos.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_reg_prestamos.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.btn_reg_prestamos.setObjectName("btn_reg_prestamos")
        self.horizontalLayout_20.addWidget(self.btn_reg_prestamos)
        spacerItem9 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.stackedWidget.addWidget(self.Prestamos)
        self.R_L_2 = QtWidgets.QWidget()
        self.R_L_2.setObjectName("R_L_2")
        self.label_15 = QtWidgets.QLabel(self.R_L_2)
        self.label_15.setGeometry(QtCore.QRect(9, 9, 300, 20))
        self.label_15.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.layoutWidget12 = QtWidgets.QWidget(self.R_L_2)
        self.layoutWidget12.setGeometry(QtCore.QRect(11, 37, 821, 461))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_6.addWidget(self.lineEdit_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_29.addWidget(self.lineEdit_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_30.addWidget(self.label_18)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_30.addWidget(self.lineEdit_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_31.addWidget(self.label_19)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_31.addWidget(self.lineEdit_15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_33.addWidget(self.label_20)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.layoutWidget12)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_33.addWidget(self.dateEdit_2)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_32.addWidget(self.label_21)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget12)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_32.addWidget(self.spinBox)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_32)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.btn_reg_libros = QtWidgets.QPushButton(self.layoutWidget12)
        self.btn_reg_libros.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_reg_libros.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_reg_libros.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.btn_reg_libros.setObjectName("btn_reg_libros")
        self.horizontalLayout_8.addWidget(self.btn_reg_libros)
        spacerItem11 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.R_L_2)
        self.R_L = QtWidgets.QWidget()
        self.R_L.setObjectName("R_L")
        self.label_8 = QtWidgets.QLabel(self.R_L)
        self.label_8.setGeometry(QtCore.QRect(9, 9, 300, 20))
        self.label_8.setMaximumSize(QtCore.QSize(300, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layoutWidget13 = QtWidgets.QWidget(self.R_L)
        self.layoutWidget13.setGeometry(QtCore.QRect(14, 35, 821, 461))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_22.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_22.addWidget(self.lineEdit_8)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_24.addWidget(self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_24.addWidget(self.lineEdit_9)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_25.addWidget(self.label_12)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget13)
        self.dateEdit.setMinimumSize(QtCore.QSize(300, 30))
        self.dateEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_25.addWidget(self.dateEdit)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_27.addWidget(self.label_13)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_27.addWidget(self.lineEdit_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_28.addWidget(self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_28.addWidget(self.lineEdit_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.btn_reg_Lector = QtWidgets.QPushButton(self.layoutWidget13)
        self.btn_reg_Lector.setMinimumSize(QtCore.QSize(250, 20))
        self.btn_reg_Lector.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_reg_Lector.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 167, 69); /* Verde */\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 60 9pt \"Arial Black\";\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 201, 91); /* Verde más claro */\n"
"    color: white;\n"
"}")
        self.btn_reg_Lector.setObjectName("btn_reg_Lector")
        self.horizontalLayout_11.addWidget(self.btn_reg_Lector)
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.R_L)
        self.verticalLayout_17.addWidget(self.stackedWidget)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.Iconos_only = QtWidgets.QFrame(self.centralwidget)
        self.Iconos_only.setMinimumSize(QtCore.QSize(100, 100))
        self.Iconos_only.setMaximumSize(QtCore.QSize(0, 16777215))
        self.Iconos_only.setStyleSheet("QWidget{\n"
"background-color: rgb(50, 50, 50);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(61,61,61);\n"
"border-radius:20px;\n"
"color: rgb(255,255,255);\n"
"font: 60 7pt \"Arial Black\";\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-radius:20px;\n"
"color: rgb(0,0,0);\n"
"font: 60 7pt \"Arial Black\";\n"
"}")
        self.Iconos_only.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Iconos_only.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Iconos_only.setObjectName("Iconos_only")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Iconos_only)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.label_3 = QtWidgets.QLabel(self.Iconos_only)
        self.label_3.setMinimumSize(QtCore.QSize(40, 40))
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/biblioteca-en-linea.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem15 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_Home = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_Home.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_Home.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/hogar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Home.setIcon(icon2)
        self.bt_Home.setIconSize(QtCore.QSize(35, 35))
        self.bt_Home.setCheckable(True)
        self.bt_Home.setChecked(False)
        self.bt_Home.setAutoExclusive(True)
        self.bt_Home.setObjectName("bt_Home")
        self.verticalLayout_2.addWidget(self.bt_Home)
        self.bt_usuario = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_usuario.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_usuario.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/agregar-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_usuario.setIcon(icon3)
        self.bt_usuario.setIconSize(QtCore.QSize(35, 35))
        self.bt_usuario.setCheckable(True)
        self.bt_usuario.setAutoExclusive(True)
        self.bt_usuario.setObjectName("bt_usuario")
        self.verticalLayout_2.addWidget(self.bt_usuario)
        self.bt_libros = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_libros.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_libros.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/librogfdsgsdg0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_libros.setIcon(icon4)
        self.bt_libros.setIconSize(QtCore.QSize(35, 35))
        self.bt_libros.setCheckable(True)
        self.bt_libros.setAutoExclusive(True)
        self.bt_libros.setObjectName("bt_libros")
        self.verticalLayout_2.addWidget(self.bt_libros)
        self.bt_prestamos = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_prestamos.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_prestamos.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/libro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_prestamos.setIcon(icon5)
        self.bt_prestamos.setIconSize(QtCore.QSize(35, 35))
        self.bt_prestamos.setCheckable(True)
        self.bt_prestamos.setAutoExclusive(True)
        self.bt_prestamos.setObjectName("bt_prestamos")
        self.verticalLayout_2.addWidget(self.bt_prestamos)
        self.bt_devoluciones = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_devoluciones.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_devoluciones.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/return_5597034.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_devoluciones.setIcon(icon6)
        self.bt_devoluciones.setIconSize(QtCore.QSize(35, 35))
        self.bt_devoluciones.setCheckable(True)
        self.bt_devoluciones.setChecked(True)
        self.bt_devoluciones.setAutoExclusive(True)
        self.bt_devoluciones.setObjectName("bt_devoluciones")
        self.verticalLayout_2.addWidget(self.bt_devoluciones)
        self.bt_devoluciones_2 = QtWidgets.QPushButton(self.Iconos_only)
        self.bt_devoluciones_2.setMinimumSize(QtCore.QSize(70, 50))
        self.bt_devoluciones_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/reporte-anual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_devoluciones_2.setIcon(icon7)
        self.bt_devoluciones_2.setIconSize(QtCore.QSize(35, 35))
        self.bt_devoluciones_2.setCheckable(True)
        self.bt_devoluciones_2.setChecked(True)
        self.bt_devoluciones_2.setAutoExclusive(True)
        self.bt_devoluciones_2.setObjectName("bt_devoluciones_2")
        self.verticalLayout_2.addWidget(self.bt_devoluciones_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.Iconos_only, 0, 0, 1, 1)
        self.Full_menu = QtWidgets.QFrame(self.centralwidget)
        self.Full_menu.setMinimumSize(QtCore.QSize(180, 180))
        self.Full_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.Full_menu.setStyleSheet("QWidget{\n"
"background-color: rgb(50, 50, 50);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(61,61,61);\n"
"border-radius:20px;\n"
"color: rgb(255,255,255);\n"
"font: 60 7pt \"Arial Black\";\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-radius:20px;\n"
"color: rgb(0,0,0);\n"
"font: 60 7pt \"Arial Black\";\n"
"}")
        self.Full_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Full_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Full_menu.setObjectName("Full_menu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Full_menu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.Full_menu)
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/biblioteca-en-linea.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.Full_menu)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(255,255,255);\n"
"font: 60 8pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Home = QtWidgets.QPushButton(self.Full_menu)
        self.btn_Home.setMinimumSize(QtCore.QSize(70, 50))
        self.btn_Home.setStyleSheet("QPushButton{\n"
"\n"
"text-align:center\n"
"}")
        self.btn_Home.setIcon(icon2)
        self.btn_Home.setIconSize(QtCore.QSize(35, 35))
        self.btn_Home.setCheckable(True)
        self.btn_Home.setChecked(False)
        self.btn_Home.setAutoExclusive(True)
        self.btn_Home.setObjectName("btn_Home")
        self.verticalLayout.addWidget(self.btn_Home)
        self.btn_usuario = QtWidgets.QPushButton(self.Full_menu)
        self.btn_usuario.setMinimumSize(QtCore.QSize(70, 50))
        self.btn_usuario.setStyleSheet("QPushButton{\n"
"\n"
"text-align:left\n"
"}")
        self.btn_usuario.setIcon(icon3)
        self.btn_usuario.setIconSize(QtCore.QSize(35, 35))
        self.btn_usuario.setCheckable(True)
        self.btn_usuario.setChecked(False)
        self.btn_usuario.setAutoExclusive(True)
        self.btn_usuario.setObjectName("btn_usuario")
        self.verticalLayout.addWidget(self.btn_usuario)
        self.btn_libros = QtWidgets.QPushButton(self.Full_menu)
        self.btn_libros.setMinimumSize(QtCore.QSize(70, 50))
        self.btn_libros.setStyleSheet("QPushButton{\n"
"\n"
"text-align:left\n"
"}")
        self.btn_libros.setIcon(icon4)
        self.btn_libros.setIconSize(QtCore.QSize(35, 35))
        self.btn_libros.setCheckable(True)
        self.btn_libros.setAutoExclusive(True)
        self.btn_libros.setObjectName("btn_libros")
        self.verticalLayout.addWidget(self.btn_libros)
        self.btn_prestamos = QtWidgets.QPushButton(self.Full_menu)
        self.btn_prestamos.setMinimumSize(QtCore.QSize(70, 50))
        self.btn_prestamos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_prestamos.setStyleSheet("QPushButton{\n"
"\n"
"text-align:left\n"
"}")
        self.btn_prestamos.setIcon(icon5)
        self.btn_prestamos.setIconSize(QtCore.QSize(35, 35))
        self.btn_prestamos.setCheckable(True)
        self.btn_prestamos.setAutoExclusive(True)
        self.btn_prestamos.setObjectName("btn_prestamos")
        self.verticalLayout.addWidget(self.btn_prestamos)
        self.pushButton_6 = QtWidgets.QPushButton(self.Full_menu)
        self.pushButton_6.setMinimumSize(QtCore.QSize(70, 50))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"\n"
"text-align:left\n"
"}")
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setChecked(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.Full_menu)
        self.pushButton_7.setMinimumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"\n"
"text-align:left\n"
"}")
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setChecked(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(17, 167, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.Full_menu, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton.toggled['bool'].connect(self.Iconos_only.setVisible) # type: ignore
        self.pushButton.toggled['bool'].connect(self.Full_menu.setHidden) # type: ignore
        self.bt_usuario.toggled['bool'].connect(self.btn_usuario.setChecked) # type: ignore
        self.bt_libros.toggled['bool'].connect(self.btn_libros.setChecked) # type: ignore
        self.bt_prestamos.toggled['bool'].connect(self.btn_prestamos.setChecked) # type: ignore
        self.bt_devoluciones.toggled['bool'].connect(self.pushButton_6.setChecked) # type: ignore
        self.btn_usuario.toggled['bool'].connect(self.bt_usuario.setChecked) # type: ignore
        self.btn_libros.toggled['bool'].connect(self.bt_libros.setChecked) # type: ignore
        self.btn_prestamos.toggled['bool'].connect(self.bt_prestamos.setChecked) # type: ignore
        self.pushButton_6.toggled['bool'].connect(self.bt_devoluciones.setChecked) # type: ignore
        self.btn_Home.toggled['bool'].connect(self.bt_Home.setChecked) # type: ignore
        self.bt_Home.toggled['bool'].connect(self.btn_Home.setChecked) # type: ignore
        self.bt_devoluciones_2.toggled['bool'].connect(self.pushButton_7.setChecked) # type: ignore
        self.pushButton_7.toggled['bool'].connect(self.bt_devoluciones_2.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "BIENVENIDO AL SISTEMA DE BIBLIOTECA"))
        self.label_37.setText(_translate("MainWindow", "LIBROS"))
        self.label_38.setText(_translate("MainWindow", "  0"))
        self.label_58.setText(_translate("MainWindow", "LECTORES"))
        self.label_59.setText(_translate("MainWindow", "  0"))
        self.label_40.setText(_translate("MainWindow", "PRESTAMOS"))
        self.label_41.setText(_translate("MainWindow", "  0"))
        self.label_27.setText(_translate("MainWindow", "DEVULETOS"))
        self.label_29.setText(_translate("MainWindow", "  0"))
        self.pushButton_9.setText(_translate("MainWindow", "GENERAR REPORTE"))
        self.checkBox.setText(_translate("MainWindow", "TODOS LOS LIBROS"))
        self.checkBox_2.setText(_translate("MainWindow", "TODOS LOS LECTORES"))
        self.checkBox_3.setText(_translate("MainWindow", "TODOS LOS PRESTAMOS"))
        self.checkBox_4.setText(_translate("MainWindow", "TODOS LAS DEVOLUCIONES"))
        self.checkBox_5.setText(_translate("MainWindow", "LIBROS MAS PRESTADOS"))
        self.checkBox_7.setText(_translate("MainWindow", "LIBROS DISPONIBLES"))
        self.checkBox_6.setText(_translate("MainWindow", "LIBROS NO DISPONIBLE"))
        self.checkBox_8.setText(_translate("MainWindow", "LIBROS NO DEVUELTOS"))
        self.checkBox_9.setText(_translate("MainWindow", "LECTOR MAS FRECUENTE"))
        self.label_25.setText(_translate("MainWindow", "SELECCIONE LO QUE GENERARA EL REPORTE"))
        self.label_54.setText(_translate("MainWindow", "CI Lector"))
        self.pushButton_21.setText(_translate("MainWindow", "BUSCAR"))
        self.pushButton_10.setText(_translate("MainWindow", "GENERAR REPORTE"))
        self.pushButton_5.setText(_translate("MainWindow", "REPORTE GENERAL"))
        self.pushButton_8.setText(_translate("MainWindow", "REPORTE DE LECTORES"))
        self.label_5.setText(_translate("MainWindow", "DEVOLUCIONES"))
        self.label_6.setText(_translate("MainWindow", "CODIGO"))
        self.pushButton_3.setText(_translate("MainWindow", "BUSCAR"))
        self.label_7.setText(_translate("MainWindow", "FECHA DEVOLUCION"))
        self.label_22.setText(_translate("MainWindow", "ESTADO"))
        self.label_23.setText(_translate("MainWindow", "OBSERVACIONES"))
        self.pushButton_4.setText(_translate("MainWindow", "GUARDAR CAMBIOS"))
        self.label_28.setText(_translate("MainWindow", "REGISTRAR PRESTAMOS DE LIBROS"))
        self.label_48.setText(_translate("MainWindow", "CI Lector"))
        self.pushButton_19.setText(_translate("MainWindow", "BUSCAR"))
        self.label_49.setText(_translate("MainWindow", "Nombre y Apellido:"))
        self.label_50.setText(_translate("MainWindow", "TItulo del Libro:"))
        self.label_51.setText(_translate("MainWindow", "Fecha de Reserva"))
        self.label_52.setText(_translate("MainWindow", "Fecha de Devolucion"))
        self.label_53.setText(_translate("MainWindow", "Cantidad de Libros"))
        self.btn_reg_prestamos.setText(_translate("MainWindow", "REGSTRAR"))
        self.label_15.setText(_translate("MainWindow", "REGISTRAR LIBRO"))
        self.label_16.setText(_translate("MainWindow", "TITULO"))
        self.label_17.setText(_translate("MainWindow", "AUTOR"))
        self.label_18.setText(_translate("MainWindow", "GENERO"))
        self.label_19.setText(_translate("MainWindow", "EDICION"))
        self.label_20.setText(_translate("MainWindow", "AÑO PUBLICADO"))
        self.label_21.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_reg_libros.setText(_translate("MainWindow", "REGSTRAR"))
        self.label_8.setText(_translate("MainWindow", "REGISTRAR DATOS DEL LECTOR"))
        self.label_9.setText(_translate("MainWindow", "Nombre"))
        self.label_10.setText(_translate("MainWindow", "Apellido"))
        self.label_11.setText(_translate("MainWindow", "CI"))
        self.label_12.setText(_translate("MainWindow", "Fecha De Nacimiento"))
        self.label_13.setText(_translate("MainWindow", "Telefono"))
        self.label_14.setText(_translate("MainWindow", "Direccion"))
        self.btn_reg_Lector.setText(_translate("MainWindow", "REGSTRAR"))
        self.label_2.setText(_translate("MainWindow", "BIBLIOTECA"))
        self.btn_Home.setText(_translate("MainWindow", "HOME"))
        self.btn_usuario.setText(_translate("MainWindow", "REGISTRAR LECTOR"))
        self.btn_libros.setText(_translate("MainWindow", "REGISTRAR LIBRO"))
        self.btn_prestamos.setText(_translate("MainWindow", "PRESTAMOS"))
        self.pushButton_6.setText(_translate("MainWindow", "DEVOLUCIONES"))
        self.pushButton_7.setText(_translate("MainWindow", "REPORTES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
